repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        language_version: python3
        additional_dependencies:
        -   types-requests
        -   types-PyYAML
        -   types-Pillow
        -   types-protobuf
        -   types-setuptools
        -   mypy-protobuf
        files: "mir/.*"
        exclude: "[cmd.py|.*pb2.py]"
        args:
        -   "--ignore-missing-imports"
