# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-ci.txt
    - name: mypy
      run: |
        mypy mir
    - name: flake8
      run: |
        flake8 mir
    - name: Test with pytest
      run: |
        git config --global user.name 'Deployer'
        git config --global user.email 'deployer@intellif.com'
        python tests/__main__.py
